# Week 2

In the second week we discussed version control using Github and had a refresher about Python programming.

## Version Control

### What is Version Control


[https://en.wikipedia.org/wiki/Version_control]

Most famous VCS are;

Git
Subversion
Mercurial

In this course, we will use Git.

#### Terminology

*Version Control System / Source Code Manager*

Git is a SCM or VCS that stores the status of the files for us.

*Commit*
When a commit is made Git stores the contents of all the files that are in the staging area. It is like saving in a game.

*Repository / repo*
A repository is a directory that contains your project.


*Working Directory*
Working Directory is the directory that is configured in the init for the repo.

*Checkout*
A checkout is when content in the repository has been copied to the Working Directory.

*Staging Area / Staging Index / Index*
A file in the Git directory that stores information about what will go into your next commit. You can think of the staging area as a prep table where Git will take the next commit. Files on the Staging Index are poised to be added to the repository.

*SHA*
A SHA is basically an ID number for each commit. Here's what a commit's SHA might look like: e2adf8ae3e2e4ed40add75cc44cf9d0a869afeb6.

It is a 40-character string composed of characters (0–9 and a–f) and calculated based on the contents of a file or directory structure in Git. "SHA" is shorthand for "Secure Hash Algorithm". If you're interested in learning about hashes, check out our Intro to Computer Science course.

*Branch*
A branch is when a new line of development is created that diverges from the main line of development. This alternative line of development can continue without altering the main line.

### Create a Git Repo

### Add Commits to a Repo

### Branching and Merging

### Repo's History

### Undoing Changes

Modifying the Last Commit

`git commit --amend`

Reverting a Commit

`git revert <SHA of a commit>`

Deleting a Commit
can be dangerous
`git reset`



Optional readings are below:

  - Reading:
    - [Excuse me, do you have a moment to talk about version control?](https://peerj.com/preprints/3159/)
